<paste log output from Kubernetes-mediated prediction, here>
Error from server (AlreadyExists): pods "udacitymicroservicenew" already exists
NAME                     READY   STATUS    RESTARTS   AGE
udacitymicroservicenew   1/1     Running   0          20m
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

[2021-08-15 09:47:31,024] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-08-15 09:47:31,038] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-08-15 09:47:31,048] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-08-15 09:47:31,051] INFO in app: output prediction: [20.35373177134412]
172.17.0.1 - - [15/Aug/2021 09:47:31] "POST /predict HTTP/1.1" 200 -
